.flexci/lint.sh, .github/workflows/lint.yaml, pyproject.toml, tools/lint/Dockerfile, tools/lint/requirements.txt, tools/lint/run_docker.sh
lintをgithub actionsでも実行するようにします
=> Add lint on github actions

python/kachaka_api/aio/__init__.py
=> fix bug where wrong field is referenced in the loop

python/kachaka_api/aio/__init__.py
odometry を取得するcallbackを設定する機能を実装します
=> add set_ros_odometry_callback as well

python/kachaka_api/geometry_util.py
RosOdometry.pose.pose.orientation のquaternionをz軸周りの回転角度として扱うための関数です。odometryを扱うときにあると便利なのでutilにほしいです。
=> utility to calculate the yaw from quaternion

python/kachaka_api/aio/base.py, python/kachaka_api/base.py
start_commandで実行される関数にwait_for_completion引き数を足します。
この引き数が Trueの場合は、関数はコマンドが終了することを待ち、終了結果がreturnされます。
これまでと挙動が変わってしまいますが、wait_for_completionがTrueの動作のほうが直感的なため相談の上デフォルト Trueとしました。
=> Add wait_for_completion option to commands

ros2/kachaka_description/config/kachaka.rviz
RVizコンフィグが色が変になっていたりしていたので修正します。
After
Before
=> Fix kachaka.rviz

python/demos/README_SMART_SPEAKER.md
リクエストのBodyに"data"を含むJSONがないとエラーとなったため追加しました。
また、Activate sentenceではなくActivate sceneとなっています。
=> Correct some instructions for connecting to Google Assistant

ros2/kachaka_grpc_ros2_bridge/src/component/robot_info_component.cpp
バッテリ残量と充電状態をROS2のトピックで出力するようにしました。
=> add ros2 topics for battery percentage and power supply status

python/demos/emergency_stop.py
=> emergency stop demo: fixed typo

ros2/kachaka_grpc_ros2_bridge/package.xml, tools/ros2_bridge/docker-compose.yaml
I resolved <https://github.com/pf-robotics/kachaka-api/issues/104>.
- I add `cyclonedds` and `rmw_cyclonedds_cpp` to the dependency of `kachaka_grpc_ros2_bridge`.
- I add `RMW_IMPLEMENTATION` to docker-compose.yaml.
=> Support Cyclone DDS

ros2/kachaka_grpc_ros2_bridge/src/component/mapping_component.cpp
https://github.com/pf-robotics/kachaka-api/issues/120
で報告していた件についてバグ調査を行い、おそらく原因と思われる箇所を特定できましたので、
修正したPRになります。この修正で、/kachaka/mapping/mapのトピック配信が行われるように
なりました。tools/lint/local_run.shは通しております。
ご確認よろしくおねがいします。
=> bugfix: checking logic for empty map data was wrong

python/kachaka_api/aio/base.py, python/kachaka_api/base.py
=> Fix battery attribute

pyproject.toml
=> Change version to v3.7.6

ros2/kachaka_grpc_ros2_bridge/src/camera_bridge.hpp, ros2/kachaka_grpc_ros2_bridge/src/component/dynamic_tf_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/component/imu_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/component/lidar_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/component/mapping_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/component/odometry_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/component/static_tf_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/component/wheel_odometry_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/dynamic_tf_bridge.cpp
main ブランチ上で lint エラーが出ているので、修正します。
`./tools/lint/run_docker.sh -i` を実行しただけです。
=> Apply formatter

docs/kachaka_api_client.ipynb, docs/kachaka_api_client_async.ipynb
docsのAPIを一覧するドキュメントから充電状態・充電残量の取得の説明が抜けていたので追加します。
=> added description about battery status acquisition

docs/kachaka_api_client.ipynb, docs/kachaka_api_client_async.ipynb
以下の２つのファイルの間に微妙な差があるので、それを修正します。
kachaka_api_client.ipynb
kachaka_api_client_async.ipynb
特に本質的な変更はしていません。
=> Minimize diff between sync/async client sample code

pyproject.toml
release作業です。
versionを3.9.5に上げます。
=> Update release version

ros2/kachaka_description/urdf/_kachaka.urdf.xacro
I refactored `_kachaka.urdf.xacro`.
=> refactor _kachaka.urdf.xacro

docs/kachaka_api_client.ipynb, docs/kachaka_api_client_async.ipynb
=> Fix broken links

ros2/demos/kachaka_nav2_bringup/launch/navigation_launch.py
https://github.com/pf-robotics/kachaka-api/issues/187 の修正を行いました。
=> Fixed the handling of autostart in navigation_launch.py

python/kachaka_api/aio/base.py, python/kachaka_api/base.py
dock any shelfで、他のmove shelfやmove to location同様にIDだけでなく名前でも目的地を指定できるようにします。
=> allow specifying location name as dock_any_shelf arg

pyproject.toml
pyproject.tomlのversionを3.11.11にあげます。
=> update version 3.11.11 in pyproject.toml
