pf-robotics/kachaka-api

README.md
When using `utils/set_authorized_keys_from_github.ipynb` to set up `authorized_keys`, there is no need to paste the public key into `public_keys`.
=> Fix instructions on utils/set_authorized_keys_from_github.ipynb

python/kachaka_api/geometry_util.py
従来、MapImage2DGeometryの中で行列を変換する処理を隠蔽していました。しかし複数のベクトルを同時に変換するなどの行列をそのまま使いたいケースがあるのでpublicな名前にしたいです。
=> expose the function to calculate transform matrix

python/kachaka_api/aio/base.py, python/kachaka_api/base.py
get_auto_homing_enabledがkachaka-apiに欠けていたので足します。
改めて確認しましたが、欠けていたのはこれだけでした
=> Add get_auto_homing_enabled to kachaka-api

python/kachaka_api/aio/__init__.py
```
message GetRobotVersionResponse {
Metadata metadata = 1;
string version = 2;
}
```
なので、`response.version`を取得するところが`response.robot_version`となっていたので修正します。
=> fixed field name to get robot version

README.md
kachaka_startup.sh を使って自動起動する際に、標準出力のバッファリングを無効にしないとログの確認が難しくなってしまうので、-u を追記します。
=> Add -u to python3 not to buffer stdout

python/demos/url_kachaka_api.ipynb
すみません、手元で動作確認したpythonをコピペしたときにローカルのURLが残ってました:bow:
=> Fix url api demo

ros2/kachaka_grpc_ros2_bridge/src/component/mapping_component.cpp
AB#13133
occupancy
gridの値がcolorのpngをdecodeされたものになっていたので、occupancyが全てUnkownになっていました。
GRPCからColorでないインターフェイスを作って伝搬させたほうが良いのですが、実質３値しか使っていないのでこの方法で治します。
=> correct occupancy grid value (#174)

pyproject.toml, python/demos/sample_llm_speak.py, python/kachaka_api/aio/__init__.py
kachaka_api/aio/__init__.py をmypyかけるのついでにコード重複周りを リファクタリグしました。
genericsにしておくことでset_callbackに相当するような新しいを機能XXXX追加するときに、ResponseHandlerに追加するだけ済むようになります。e.g. `client.robot_pose.XXXX`
下記のcallbackをは提供する必要もなさそうだったので消しました
- serial_number
- robot_id
- front_camera_ros_camera_info
また、locationに依存するcallbackが複数あると複雑になる & callbackあまり必要になさそうなので、
default_location_idのcallbackも削除しました。
参考: https://docs.python.org/ja/3.10/library/typing.html
=> Refactor and mypy to kachaka_api/aio/__init__.py

pyproject.toml, python/demos/sample_llm_speak.py, python/kachaka_api/__init__.py, python/kachaka_api/aio/base.py, python/kachaka_api/base.py, python/kachaka_api/util/command.py, python/kachaka_api/util/geometry.py, python/kachaka_api/util/layout.py, tools/lint/local_run.sh
kachaka_api.xxx_utilに対するmypyを有効化します。
既存のディレクトリ構成だとgenerated避けをするのに不便だったので、xxx_util.pyをutil/xxx.pyに移動しました。
__init__.pyで xxx_utilとしてimportしているのでこれまでのコードもそのまま動きます。
また、なぜかpysen経由の呼び出しだとmypyがnumpyまわりを一部うまく解決してくれないので、mypyはpysen経由ではなくそのまま呼ぶことにしました。
=> mypy to utils

python/demos/get_front_camera.ipynb
フロントカメラから画像を1枚取得するサンプルを、KachakaApiClientを使うものに差し替えます。
また生画像1枚を取得する例のみだったのを、圧縮画像と生画像を1枚ずつ取得する例にしておきます。
(連続画像取得のサンプルはaioを使ったものなので、これで過不足なくしておきたいです)
=> Use kachaka client in get_front_camera sample

python/demos/get_front_camera_continuous.ipynb, python/demos/get_object_detection.ipynb, python/demos/url_kachaka_api.ipynb
KachakaApiClientを使う際はデフォルトで"100.94.1.1:26400"が指定されているので、必要ない引数指定を辞めます。
https://github.com/pf-robotics/kachaka-api/blob/main/python/kachaka_api/aio/base.py#L22
(setup_demo_envからkachaka_api_serverも消したいですが、 demos内のサンプルを全てKachakaApiClient利用に移行させてからですね)
=> remove unnecessary input argument in KachakaApiClient initialization

python/kachaka_api/aio/base.py, python/kachaka_api/base.py
This reverts commit 511f7198de8cd115f49f39f87051ac58abfccb37.
Historyfには
* move_to_location
* move_shelf
* return_shelf
* return_home
しか載らないという使用があり、その他のコマンドが動かなくなってしまっていたので一旦revertします
=> Revert "Add wait_for_completion option to commands (#44)"

python/kachaka_api/aio/base.py, python/kachaka_api/base.py
指令値が-1~1に正規化される仕様でした。
ROS2同様にset_robot_velocityもm/s, rad/sで指定できるようにします
=> Allow set_velocity to be specified in m/s and rad/s

python/kachaka_api/aio/base.py, python/kachaka_api/base.py
manual_control_enable ROS2では、set_robot_velocityが失敗したら投げているとのこと。なるほどとなったのでkachaka_apiでも同じようにします。
disableも自然にできると良さそう & set_robot_velocity はロボットが速度を一定時間保有してしまう都合上明示的に止めたほうがよいので、set_robot_stopも合わせて足しました
=> Call set_manual_control automatically when set_robot_velocity called

ros2/demos/kachaka_bringup/bringup/package.xml
kachaka_bringup/bringupのpackage.xmlのメンテナーなどの情報がコピー元と思われるもののままであったため、修正しました。
=> Fix package.xml tags of kachaka_bringup/bringup

ros2/kachaka_description/config/kachaka.rviz, ros2/kachaka_grpc_ros2_bridge/src/component/camera_component.cpp
これまでは `/kachaka/front_camera/camera_info` しかなかったので、CompressedImageをRViz2などで利用するには以下のようにremapする必要がありました。
```
rviz2 --ros-args --remap /kachaka/front_camera/image_raw/camera_info:=/kachaka/front_camera/camera_info
```
このPRでは`/kachaka/front_camera/image_raw/camera_info` を追加し、remapの必要をなくします。
`kachaka.rviz`も修正して、画像更新が早くなったことを確認済み。
=> Add /kachaka/front_camera/image_raw/camera_info

ros2/kachaka_grpc_ros2_bridge/CMakeLists.txt, ros2/kachaka_grpc_ros2_bridge/launch/grpc_ros2_bridge.launch.xml, ros2/kachaka_grpc_ros2_bridge/src/camera_bridge.hpp, ros2/kachaka_grpc_ros2_bridge/src/component/front_camera_component.cpp
CameraComponentをリファクタリングし、CameraBridgeとそれを呼ぶFrontCameraComponentに分割しました。将来的に後ろカメラコンポーネントなどを追加しやすくするためです。動作に変化はありません。動作確認済み。
=> Refactor CameraComponent by separating CameraBridge and FrontCameraComponent

ros2/demos/kachaka_follow/package.xml
ROS 2 Humble以降で`geometry_msgs`は単体パッケージでは配られていないので、それを内包する`common_interface`に依存するようにしました。
```
$ rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
kachaka_follow: Cannot locate rosdep definition for [geoemetry_msgs]
```
=> kachaka_follow depends common_interfaces instead

python/demos/requirements.txt
未対応のnumpy 2.0がインストールされてしまうのを防ぐ為、numpyのバージョンを固定しておきます。
https://github.com/pf-robotics/kachaka-api/discussions/94
=> specify numpy version in requirements.txt

ros2/demos/kachaka_nav2_bringup/params/nav2_params.yaml
<https://github.com/pf-robotics/kachaka-api/issues/106>の対応です。kachaka_nav2_bringupパッケージのnavigation_launch.py実行時に以下のエラーが発生し、map、odom間の変換が正常にできずに経路追従に失敗して走行ががたつくことがある問題の対応です。
```
[controller_server-1] [INFO] [1721806791.956888899] [controller_server]: Passing new path to controller.
[controller_server-1] [ERROR] [1721806792.114764736] [tf_help]: Transform data too old when converting from odom to map
[controller_server-1] [ERROR] [1721806792.114836098] [tf_help]: Data time: 1721806792s 88418722ns, Transform time: 1721806791s 859294000ns
```
=> Changed transform_tolerance of FollowPath

README.md
<https://github.com/pf-robotics/kachaka-api/issues/6>、<https://github.com/pf-robotics/kachaka-api/issues/102>に関連します。<https://github.com/pf-robotics/kachaka-api/blob/main/Dockerfile.ros2>を使ってDockerイメージをビルドする手順をREADMEに追記しました。実行コマンドは<https://github.com/pf-robotics/kachaka-api/issues/6#issuecomment-1683646465>にあるものを参考にし、CPUアーキテクチャに関する説明を追記しています。また、自身でDockerイメージを作成した場合、<https://github.com/pf-robotics/kachaka-api/blob/main/tools/ros2_bridge/docker-compose.yaml>の変更が必要になるため、その説明を追記しています。
=> add step to build docker image in README

ros2/demos/kachaka_nav2_bringup/rviz/kachaka-nav.rviz
`kachaka_nav2_bringup/rviz/kachaka-nav.rviz`の更新をしました。変更点は配下の通りです。
- 占有格子地図（mapトピック）の描画設定をDraw Behind=Trueにする
- 現状のコストマップ、占有格子地図の描画順だと視認性が悪いため
- `nav2_rviz_plugins/Navigation`パネル追加
- navigation2のステータスを可視化するため
- ゴール指定を`nav2_rviz_plugins/GoalTool`に変更
- RViz2パネルからWaypoint指定するため
- scanの可視化方法変更
- 白色、Flat Squaresだと視認性が悪いため
- 視点変更
- デフォルトだと地図の原点から離れた場所に視点があるため
- Waypoint可視化
- Waypoint指定時に可視化するため
=> Updated kachaka-nav.rviz

python/kachaka_api/__init__.py, python/kachaka_api/aio/base.py, python/kachaka_api/base.py
型ヒントまわりで問題がある箇所を修正します。
* `__init__` の返り値型に None をつける
* py.typedを配置 (PEP561に準拠)
=> refined type annotation and place py.typed

pyproject.toml
PyPIでの公開の準備として、pyproject.tomlのバージョンがずっと変わっていないままだったので、バージョン番号を合わせます。(今後はリリースのたびに適切に更新する)
=> specify correct version in pyproject.toml

pyproject.toml, uv.lock
pyproject.tomlで記述しているdependenciesにバージョン指定をするようにします。
また、これに合わせてuv.lockを追加します。(uvを使っている人なら環境を再現しやすくなります)
=> specify depends version and support uv

ros2/kachaka_description/config/display.rviz, ros2/kachaka_description/launch/robot_display.launch.xml
本PRでは，RViz上のロボット可視化のためのノードの起動機能を追加しました．
主な変更点は，新しいRViz設定ファイルとロボットモデルを表示するための新しいlaunchファイルの追加です．
* 新しいlaunchファイル `robot_display.launch.xml` を追加し, `RViz`と`Joint State Publisher`を起動できるようにしました．
* 名前空間, フレームプレフィックス, GUI使用の引数に対応しています．
=> [ROS2] Add URDF display function with Rviz2 for debug

README.md
以下のURLでkachaka-apiを公開するようにしたので、pip installの節を更新します。
https://pf-robotics.github.io/kachaka-python-packages/simple
=> fixed description about installing of kachaka-api via pip

ros2/kachaka_description/launch/robot_description.launch.xml, ros2/kachaka_grpc_ros2_bridge/launch/grpc_ros2_bridge.launch.xml, ros2/kachaka_grpc_ros2_bridge/src/camera_bridge.hpp, ros2/kachaka_grpc_ros2_bridge/src/component/back_camera_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/component/diagnostics_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/component/dynamic_tf_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/component/front_camera_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/component/imu_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/component/lidar_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/component/mapping_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/component/odometry_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/component/static_tf_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/component/tof_camera_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/component/wheel_odometry_component.cpp, ros2/kachaka_grpc_ros2_bridge/src/converter/ros_header.cpp, ros2/kachaka_grpc_ros2_bridge/src/converter/ros_header.hpp, ros2/kachaka_grpc_ros2_bridge/src/dynamic_tf_bridge.cpp, ros2/kachaka_grpc_ros2_bridge/src/dynamic_tf_bridge.hpp, tools/ros2_bridge/docker-compose.yaml, tools/ros2_bridge/start_bridge.sh
このPRでは, `kachaka_grpc_ros2_bridge` パッケージにおいて, `tf` フレーム名にプレフィックスと`namespace`を設定できる機能を追加しました．この変更により, Issue https://github.com/pf-robotics/kachaka-api/issues/136 に書かれたように同一の`ROS_DOMAIN_ID`でもマルチロボット環境での名前空間管理が可能となります．
1. 対象となるメッセージの `header.frame_id` および `child_frame_id` に, 指定されたフレームプレフィックスを付加するようコードを更新．
2. ランチパラメータ（`frame_prefix`や`namespace`）を追加し, ユーザーが指定できるように対応．  
3. 互換性を確保するために，プレフィックスが指定されない場合, 従来の挙動を維持．  
- 単一および複数ロボットのセットアップで動作を検証し, 指定されたプレフィックスが正しく適用されることを確認しました．
```bash
$ ./start_bridge.sh KACHAKA_IP_ADRESS KACHAKA_NAME
```
| `kachaka_1` | `kachaka_2` |
| --- | --- |
| ![k1](https://github.com/user-attachments/assets/e18a96db-ece7-4c08-998f-41886bb3b310) | ![k2](https://github.com/user-attachments/assets/686f6d2c-6e95-4d3d-979f-ee443e0f3cdb) |
- プレフィックスパラメータを指定せずにブリッジを起動し, …
=> [ROS2] Feature to allow multiple Kachaka robots within one same ROS_DOMAIN_ID

ros2/kachaka_grpc_ros2_bridge/CMakeLists.txt, ros2/kachaka_grpc_ros2_bridge/src/camera_bridge.hpp
https://github.com/ros-perception/vision_opencv/pull/448
cv_bridgeのincludeパスが、JazzyからROS 2の規格に合わせて cv_bridge.h -> cv_bridge.hpp にリネームされており、ビルドが通らない状況になっていました。
一応いま標準はHumbleなので、ROS_DISTROがJazzyのときにコンパイル時定数を足して、includeをスイッチするようにします。
手元のJazzy環境でビルドできるのを確認しました。
=> [ROS 2] switch include path of cv_bridge for ROS 2 jazzy

docs/api/ERROR_HANDLING.md
#153 で嘘を書いていたので修正します。
RECOVERABLEなエラーの場合のLEDは赤色回転ではなくて白色回転でした。
=> docs: fixed description about led effect on Recoverable error

docs/ROS2.md
This pull request includes a small change to the `docs/ROS2.md` file. The change corrects the relative path to the `docker-compose.yaml` file to ensure it is correctly referenced.
=> [ROS] fix docker-compose.yaml path in doc

docs/FEATURES.md
Jupyter Notebookという表記がややこのドキュメントのリンクを踏むハードルを上げている気がするので、もうちょっと読みたくなる感じにします。
=> refined description of features

docs/kachaka_api_client.ipynb, docs/kachaka_api_client_async.ipynb, python/kachaka_api/aio/base.py, python/kachaka_api/base.py
PythonのカチャカAPIライブラリで、LockとProceedがサポートされていなかったのでサポートするようにします。
=> python kachaka_api library: support lock and proceed in python sdk

pyproject.toml
pre-release ブランチを 3.10.6 に上げます。
pre-release は既に今現在の最新の main をマージ済みです。
=> Bump pre-release version to v3.10.6

docs/PYTHON.md
PyPI での kachaka_api の公開の準備が整ったので (https://pypi.org/project/kachaka-api/)、 独自のPython Package RepositoryではなくPyPIからインストールするように手順の説明を修正します。
=> fixed description to install kachaka_api library from PyPI

python/kachaka_api/aio/base.py, python/kachaka_api/base.py, python/kachaka_api/util/layout.py
pythonのkachaka_apiライブラリで、ID指定で棚や目的地を引数に与えたときに、
> Failed to get shelf id of S01
のようにエラーメッセージが出るようになっていました。ID指定か名前指定かに拘らず、必ず名前のルックアップを行う実装になっていたためです。
まずはIDとして扱い、IDとして存在しなければ名前として扱う、というフローに変更して、このエラー文章が出ることがないようにします。
本当は色々直したいところなのですが、一旦破壊的変更がないように修正します。
=> fixed logic to lookup id and name of shelves and locations

python/kachaka_api/util/layout.py
#190 の修正で、update_resolverを呼んでいないときにID指定ができなくなってしまっていました。
IDの解決に失敗したら、入力値をそのまま横流しして使うようにします。
=> passthrough user input if lookup failed

docs/ROS2.md
`Ubuntu 22.04.5 LTS` 上の `Docker version 28.3.2` で `./start_bridge.sh` を実行した場合、コンテナ名は
`ros2_bridge_ros2_bridge_1` ではなく `ros2_bridge-ros2_bridge-1` になっています。
=> fix. container name
